ZZG.WebUI/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZZG.Business.Abstract;
using ZZG.Entities;
using ZZG.WebUI.Models;

namespace ZZG.WebUI.Controllers
{
    public class AdminController : Controller
    {
        IProductService _productService;
        ICategoryService _categoryService;
        public AdminController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }
        public IActionResult ProductList()
        {
            return View(new ProductListModel()
            {

                Products = _productService.GetAll()
            });
        }
        [HttpGet]
        public IActionResult CreateProduct()
        {
            ProductModel model = new ProductModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateProduct(ProductModel model)
        {
            if (ModelState.IsValid==true)
            {
                var entity = new Product
                {
                    Name = model.Name,
                    ImageUrl = model.ImageUrl,
                    Description = model.Description,
                    Price = model.Price
                };
                _productService.Create(entity);
                return RedirectToAction("ProductList");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _productService.GetProductWithCategories((int)id);

            if (entity == null)
            {
                return NotFound();
            }
            ProductModel model = new ProductModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Description = entity.Description,
                ImageUrl = entity.ImageUrl,
                Price=entity.Price,
                SelectedCategories=entity.ProductCategories.Select(p => p.Category).ToList()
            };
            ViewBag.Categories = _categoryService.GetAll();
            return View(model);
        }
        [HttpPost]
        public IActionResult EditProduct(ProductModel model, int[] categoryIds)
        {
            if (ModelState.IsValid==true)
            {
                var entity = new Product
                {
                    Id = model.Id,
                    Name = model.Name,
                    ImageUrl = model.ImageUrl,
                    Description = model.Description,
                    Price = model.Price
                };
                _productService.Update(entity, categoryIds);
                return RedirectToAction("ProductList");
            }
             ViewBag.Categories = _categoryService.GetAll();
            return RedirectToAction("EditProduct");
        }
        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity = _productService.GetById(productId);
            if (entity != null)
            {
                _productService.Delete(entity);
            }
            return RedirectToAction("ProductList");
        }

        public IActionResult CategoryList()
        {
            return View(new CategoryListModel()
            {
                Categories = _categoryService.GetAll()
            });
        }
        [HttpGet]
        public IActionResult CreateCategory()
        {
            CategoryModel model = new CategoryModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryModel model)
        {
            if (ModelState.IsValid==true)
            {
                var entity = new Category()
                {
                    Name = model.Name
                };
                _categoryService.Create(entity);
                return RedirectToAction("CategoryList");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult EditCategory(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Category category = _categoryService.GetByIdWithProducts((int)id);
            if (category == null)
            {
                return NotFound();
            }
            var model = new CategoryModel
            {
                Id = category.Id,
                Name = category.Name,
                Products = category.ProductCategories.Select(p => p.Product).ToList()

            };
            return View(model);
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel model, int id)
        {
            if (ModelState.IsValid==true)
            {
                var entity = new Category
                {
                    Id = id,
                    Name = model.Name
                };
                _categoryService.Update(entity);
                return RedirectToAction("CategoryList");
            }
            return RedirectToAction("EditCategory");
        }
        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);
            if (entity != null)
            {
                _categoryService.Delete(entity);
            }
            return RedirectToAction("CategoryList");
        }
        [HttpPost]
        public IActionResult DeleteFromCategory(int categoryId, int productId)
        {
            _categoryService.DeleteFromCategory(categoryId, productId);


            return Redirect("/admin/editcategory/" + categoryId);
        }

    }
}

ZZG.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZZG.Business.Abstract;
using ZZG.Entities;
using ZZG.WebUI.Models;

namespace ZZG.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product == null)
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()
            });
        }
        public IActionResult List(string category, int page = 1)
        {
            const int pageSize = 2;
            return View(new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category, page, pageSize)
            });
        }
    }
}

ZZG.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZZG.WebUI</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" >
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>

    <partial name="_navbar" />
    <div class="container pt-100 mt-5">
        @RenderBody()
    </div>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ZZG.WebUI/Views/Shared/_navbar.cshtml
<nav class="nav navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">Shopping</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a asp-controller="Home" asp-action="Index" class="nav-link active">Home</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Shop" asp-action="List" class="nav-link ">Products</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link  ">Cart</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link  ">Order</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Admin" asp-action="ProductList" class="nav-link  ">Admin Product</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Admin" asp-action="CreateProduct" class="nav-link  ">Add Product</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Admin" asp-action="CategoryList" class="nav-link  ">Admin Category</a>
            </li>
            <li class="nav-item">
                <a asp-controller="Admin" asp-action="CreateCategory" class="nav-link  ">Add Categories</a>
            </li>
        </ul>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="#" class="nav-link  ">Logout</a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link  ">Login</a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link  ">Register</a>
            </li>
        </ul>
    </div>
</nav>

ZZG.WebUI/Views/Shared/_product.cshtml
@model Product
<div class="col-md-4">
    <div class="card mb-3">
        <img src="~/img/@Model.ImageUrl" alt="@Model.Name" class="img-div-pic"/>
        <div class=" card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted">
                <i class="fas fa-lira-sign"></i>@Model.Price
            </small>
            <div class="card-footer text-center" >
                <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm">Details</a>
                <a href="#" class="btn btn-outline-primary btn-sm ml-3">Add to Cart</a>
            </div>
        </div>
    </div>
</div>

ZZG.WebUI/Views/Shared/_slider.cshtml
<div id="mySlider" class="carousel slide mb-3" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#mySlider" data-slide-to="0" class="active"></li>
        <li data-target="#mySlider" data-slide-to="1"></li>
        <li data-target="#mySlider" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/slider1.png" alt="Alternate Text" class="d-block img-fluid img-div-slider" />
        </div>
        <div class="carousel-item ">
            <img src="~/img/slider2.jpg" alt="Alternate Text" class="d-block img-fluid img-div-slider" />
        </div>
        <div class="carousel-item ">
            <img src="~/img/slider3.jpg" alt="Alternate Text" class="d-block img-fluid img-div-slider" />
        </div>
    </div>
    <a href="#mySlider" data-slide="prev" class="carousel-control-prev"><span class="carousel-control-prev-icon"></span></a>
    <a href="#mySlider" data-slide="next" class="carousel-control-next"><span class="carousel-control-next-icon"></span></a>
   
</div>