ZZG.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZZG.Business.Abstract;
using ZZG.WebUI.Models;

namespace ZZG.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IProductService _productService;
        //private ICategoryService _categoryService;

        public HomeController(IProductService productService
            //,ICategoryService categoryService
            )
        {
            _productService = productService;
            //_categoryService = categoryService;
        }
        public IActionResult Index()
        {

            return View(new ProductListModel()
            {
                Products = _productService.GetAll()

            });
        }
    }
}

ZZG.WebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZZG.Business.Abstract;
using ZZG.WebUI.Models;

namespace ZZG.WebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            return View(new CategoryListViewModel()
            {
                SelectedCategory =RouteData.Values["category"]?.ToString(),
                Categories = _categoryService.GetAll()
            }); ;
        }
    }
}

ZZG.WebUI/Views/Home/Index.cshtml
@model ProductListModel
@{
    ViewData["Title"] = "Index";
}


<div class="row">
    <div class="col-md-3 mt-4">
       @await Component.InvokeAsync("CategoryList")
    </div>
    <div class="col-md-9" >
        <partial name="_slider" />
        <div class="row ">
            @foreach (var productItem in Model.Products)
            {
                <partial name="_product" for="@productItem" />
            }
        </div>
    </div>
</div>